[package]
name = "stm32wl-hal"
description = "Hardware abstraction layer for the STM32WL series microcontrollers."
readme = "README.md"

version = "0.1.0-alpha.0"
authors = ["Alex M. <alexmgit@protonmail.com>"]
edition = "2018"
license = "MIT"
keywords = ["arm", "cortex-m", "stm32", "hal"]
categories = ["embedded", "hardware-support", "no-std"]
repository = "https://github.com/newAM/stm32wl-hal"

[features]
embedded-hal = [
    "stm32wl-hal-gpio/embedded-hal"
]
stm32wl5x_cm0p = [
    "stm32wl-hal-aes/stm32wl5x_cm0p",
    "stm32wl-hal-gpio/stm32wl5x_cm0p",
    "stm32wl-hal-pka/stm32wl5x_cm0p",
    "stm32wl-hal-rcc/stm32wl5x_cm0p",
    "stm32wl-hal-rng/stm32wl5x_cm0p",
    "stm32wl-hal-subghz/stm32wl5x_cm0p",
    "stm32wl/stm32wl5x_cm0p",
]
stm32wl5x_cm4 = [
    "stm32wl-hal-aes/stm32wl5x_cm4",
    "stm32wl-hal-gpio/stm32wl5x_cm4",
    "stm32wl-hal-pka/stm32wl5x_cm4",
    "stm32wl-hal-rcc/stm32wl5x_cm4",
    "stm32wl-hal-rng/stm32wl5x_cm4",
    "stm32wl-hal-subghz/stm32wl5x_cm4",
    "stm32wl/stm32wl5x_cm4",
]
stm32wle5 = [
    "stm32wl-hal-aes/stm32wle5",
    "stm32wl-hal-gpio/stm32wle5",
    "stm32wl-hal-pka/stm32wle5",
    "stm32wl-hal-rcc/stm32wle5",
    "stm32wl-hal-rng/stm32wle5",
    "stm32wl-hal-subghz/stm32wle5",
    "stm32wl/stm32wle5",
]

[dependencies]
cfg-if = "^1"

[dependencies.stm32wl]
git = "https://github.com/newAM/stm32wl-rs.git"
rev = "031c2ecc3664c8ef3f642fbce075b2c238d5ff1b"

[dependencies.stm32wl-hal-aes]
path = "../aes"

[dependencies.stm32wl-hal-gpio]
path = "../gpio"

[dependencies.stm32wl-hal-pka]
path = "../pka"

[dependencies.stm32wl-hal-rcc]
path = "../rcc"

[dependencies.stm32wl-hal-rng]
path = "../rng"

[dependencies.stm32wl-hal-subghz]
path = "../subghz"
