[workspace]
members = [
    "hal",
    "pka-testsuite",
    "pka",
    "rng-testsuite",
    "rng",
    "subghz-testsuite-assets",
    "subghz-testsuite-rx",
    "subghz-testsuite-tx",
    "subghz",
]
default-members = [
    "hal",
    "pka",
    "rng",
    "subghz",
]
