[workspace]
resolver = "2"
members = [
    "adc-testsuite",
    "aes-testsuite",
    "ate",
    "examples",
    "hal",
    "nucleo-wl55jc-bsp",
    "pka-testsuite",
    "rng-testsuite",
    "subghz-testsuite",
]
default-members = ["hal"]

[profile.dev]
opt-level = 2

[profile.release]
debug = 2
