[workspace]
members = [
    "aes-testsuite",
    "aes",
    "examples",
    "hal",
    "iface",
    "pka-testsuite",
    "pka",
    "rcc",
    "rng-testsuite",
    "rng",
    "subghz-testsuite-assets",
    "subghz-testsuite-rx",
    "subghz-testsuite-tx",
    "subghz",
]
default-members = [
    "aes",
    "hal",
    "iface",
    "pka",
    "rcc",
    "rng",
    "subghz",
]
