[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip STM32WLE5JCIx --connect-under-reset"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[alias]
# e.g. cargo run-ex gpio-blink
run-ex = "run -p examples --target thumbv7em-none-eabi --example"

# e.g.
# cargo test-aes
# cargo test-subghz -- --probe 001D00145553500A20393256
# cargo test-subghz -- --probe 001600345553500A20393256
test-adc = "test -p adc-testsuite --target thumbv7em-none-eabi"
test-aes = "test -p aes-testsuite --target thumbv7em-none-eabi"
test-pka = "test -p pka-testsuite --target thumbv7em-none-eabi"
test-rng = "test -p rng-testsuite --target thumbv7em-none-eabi"
test-subghz = "test -p subghz-testsuite --target thumbv7em-none-eabi"

# e.g. cargo +nightly test-aes-aio
test-adc-aio = "test -p adc-testsuite --target thumbv7em-none-eabi --features aio"
test-aes-aio = "test -p aes-testsuite --target thumbv7em-none-eabi --features aio"
test-pka-aio = "test -p pka-testsuite --target thumbv7em-none-eabi --features aio"
test-rng-aio = "test -p rng-testsuite --target thumbv7em-none-eabi --features aio"
test-subghz-aio = "test -p subghz-testsuite --target thumbv7em-none-eabi --features aio"

# e.g. cargo unit
unit = "test --features stm32wl5x_cm4"
# e.g. cargo +nightly unit-aio
unit-aio = "test --features stm32wl5x_cm4,aio"
# e.g. cargo unit-little
unit-little = "test --features stm32wl5x_cm0p"
