[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip STM32WLE5JCIx --connect-under-reset"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "linker=flip-link",
]

[alias]
# e.g. cargo run-ex gpio-blink
run-ex = "run -p examples --target thumbv7em-none-eabi --example"

# e.g.
# cargo test-aes
# cargo test-subghz -- --probe 001D00145553500A20393256
# cargo test-subghz -- --probe 001600345553500A20393256
test-adc = "run -p testsuite --target thumbv7em-none-eabi --bin adc"
test-aes = "run -p testsuite --target thumbv7em-none-eabi --bin aes"
test-dac = "run -p testsuite --target thumbv7em-none-eabi --bin dac"
test-i2c = "run -p testsuite --target thumbv7em-none-eabi --bin i2c"
test-lptim = "run -p testsuite --target thumbv7em-none-eabi --bin lptim"
test-pka = "run -p testsuite --target thumbv7em-none-eabi --bin pka"
test-rcc = "run -p testsuite --target thumbv7em-none-eabi --bin rcc"
test-rng = "run -p testsuite --target thumbv7em-none-eabi --bin rng"
test-rtc = "run -p testsuite --target thumbv7em-none-eabi --bin rtc"
test-spi = "run -p testsuite --target thumbv7em-none-eabi --bin spi"
test-subghz = "run -p testsuite --target thumbv7em-none-eabi --bin subghz"
test-uart = "run -p testsuite --target thumbv7em-none-eabi --bin uart"

# e.g. cargo unit
unit = "test --features stm32wl5x_cm4"
unit-little = "test --features stm32wl5x_cm0p"
unit-nucleo = "test -p nucleo-wl55jc-bsp --features stm32wl5x_cm4"
unit-lora-e5 = "test -p lora-e5-bsp"
