[package]
name = "examples"
version = "0.1.0"
publish = false
authors = ["Alex M. <alexmgit@protonmail.com>"]
edition = "2018"

[dependencies]
defmt = "0.2"
defmt-rtt = "0.2"
defmt-test = "0.2"
stm32wl-hal = { path = "../hal", features = ["stm32wl5x_cm4", "rt"] }
rtt-target = { version = "~0.3.1", features = ["cortex-m"] }
panic-rtt-target = { version = "0.1", features = ["cortex-m"] }
nucleo-wl55jc-bsp = { path = "../nucleo-wl55jc-bsp" }
