[package]
name = "lora-e5-bsp"
description = "Board support package for the seeed LoRa-E5 development kit"
readme = "README.md"

version = "0.2.0"
authors = ["Alex Martens <alexmgit@protonmail.com>"]
edition = "2021"
rust-version = "1.56"
license = "MIT"
keywords = ["arm", "cortex-m", "stm32", "bsp", "seeed"]
categories = ["embedded", "hardware-support", "no-std"]
repository = "https://github.com/stm32-rs/stm32wlxx-hal"

[features]
defmt = ["stm32wlxx-hal/defmt"]
rt = ["stm32wlxx-hal/rt"]

[dependencies.stm32wlxx-hal]
path = "../hal"
features = ["stm32wle5"]
